import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-2 p-2 border-2 border-blue-800">
        <div className='text-blue-800'>Server Side (Layout)</div>
        {children}
      </body>
    </html>
  );
}
